/* eslint-disable jsx-a11y/alt-text */
import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';
import { NewsBrief } from '@/lib/blob-store';

// Register standard fonts if needed, or rely on defaults like Helvetica
// Font.register({ family: 'Roboto', src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/Roboto-Regular.ttf' });

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 40,
        fontFamily: 'Helvetica'
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#0F172A', // Slate 900
        paddingBottom: 10
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#0F172A'
    },
    subtitle: {
        fontSize: 12,
        color: '#64748B', // Slate 500
        marginTop: 4
    },
    section: {
        marginBottom: 15
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#334155', // Slate 700
        marginBottom: 6,
        textTransform: 'uppercase',
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
        paddingBottom: 2
    },
    text: {
        fontSize: 10,
        lineHeight: 1.5,
        color: '#334155',
        marginBottom: 8
    },
    talkingPointBox: {
        padding: 10,
        backgroundColor: '#F8FAFC',
        borderLeftWidth: 3,
        borderLeftColor: '#3B82F6', // Blue 500
        marginBottom: 10
    },
    tpTitle: {
        fontSize: 11,
        fontWeight: 'bold',
        color: '#1E293B'
    },
    tpContent: {
        fontSize: 10,
        color: '#475569',
        marginTop: 4
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        fontSize: 8,
        color: '#94A3B8'
    }
});

interface Props {
    brief: NewsBrief;
}

export const DailyReportTemplate: React.FC<Props> = ({ brief }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>Daily Market Intelligence</Text>
                <Text style={styles.subtitle}>{new Date(brief.timestamp).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })} • Prepared for Sales Team</Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Executive Summary of Market Conditions</Text>
                {/* We assume content is markdown-ish, but for PDF we just dump text. Ideally we parse paragraphs. */}
                <Text style={styles.text}>{brief.content}</Text>
            </View>

            {brief.topMiner && (
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Miner of the Day</Text>
                    <View style={{ flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#F0F9FF', padding: 10, borderRadius: 4 }}>
                        <View>
                            <Text style={{ fontSize: 16, fontWeight: 'bold', color: '#0369A1' }}>{brief.topMiner.name}</Text>
                        </View>
                        <View>
                            <Text style={{ fontSize: 16, fontWeight: 'bold', color: '#0369A1' }}>${brief.topMiner.dailyRevenue.toFixed(2)}/day</Text>
                            <Text style={{ fontSize: 8, color: '#0EA5E9' }}>Est. Revenue</Text>
                        </View>
                    </View>
                </View>
            )}

            <View style={styles.section}>
                <Text style={styles.sectionTitle}>Key Talking Points (Use in Calls)</Text>
                {brief.talkingPoints?.map((tp, i) => (
                    <View key={i} style={styles.talkingPointBox}>
                        <Text style={styles.tpTitle}>{tp.title}</Text>
                        <Text style={styles.tpContent}>{tp.content}</Text>
                    </View>
                ))}
            </View>

            <Text style={styles.footer}>
                CONFIDENTIAL: Internal Use Only. Generated by Sentient Sales Engine.
            </Text>
        </Page>
    </Document>
);
